// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qgnbwpwnyhgvxqbdhxof.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFnbmJ3cHdueWhndnhxYmRoeG9mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc2MzE0ODgsImV4cCI6MjA1MzIwNzQ4OH0.5uzf0Lppd-U2MjNGp9Qea9wAFVXQ5iDdHNMe1jzhNtU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);