export const SCORM_ERROR_CODES = {
  NO_ERROR: '0',
  GENERAL_EXCEPTION: '101',
  GENERAL_INIT_FAILURE: '102',
  ALREADY_INITIALIZED: '103',
  CONTENT_INSTANCE_TERMINATED: '104',
  GENERAL_GET_FAILURE: '301',
  GENERAL_SET_FAILURE: '351',
  GENERAL_COMMIT_FAILURE: '391',
  UNDEFINED_DATA_MODEL: '401',
  UNIMPLEMENTED_DATA_MODEL: '402',
  DATA_MODEL_ELEMENT_VALUE_NOT_INITIALIZED: '403',
  READ_ONLY_ELEMENT: '404',
  WRITE_ONLY_ELEMENT: '405',
  DATA_MODEL_ELEMENT_TYPE_MISMATCH: '406',
  DATA_MODEL_ELEMENT_VALUE_OUT_OF_RANGE: '407',
  DATA_MODEL_DEPENDENCY_NOT_ESTABLISHED: '408'
} as const;

export const ERROR_MESSAGES = {
  [SCORM_ERROR_CODES.NO_ERROR]: 'No error',
  [SCORM_ERROR_CODES.GENERAL_EXCEPTION]: 'General exception',
  [SCORM_ERROR_CODES.GENERAL_INIT_FAILURE]: 'General initialization failure',
  [SCORM_ERROR_CODES.ALREADY_INITIALIZED]: 'Already initialized',
  [SCORM_ERROR_CODES.CONTENT_INSTANCE_TERMINATED]: 'Content instance terminated',
  [SCORM_ERROR_CODES.GENERAL_GET_FAILURE]: 'General get failure',
  [SCORM_ERROR_CODES.GENERAL_SET_FAILURE]: 'General set failure',
  [SCORM_ERROR_CODES.GENERAL_COMMIT_FAILURE]: 'General commit failure',
  [SCORM_ERROR_CODES.UNDEFINED_DATA_MODEL]: 'Undefined data model',
  [SCORM_ERROR_CODES.UNIMPLEMENTED_DATA_MODEL]: 'Unimplemented data model',
  [SCORM_ERROR_CODES.DATA_MODEL_ELEMENT_VALUE_NOT_INITIALIZED]: 'Data model element value not initialized',
  [SCORM_ERROR_CODES.READ_ONLY_ELEMENT]: 'Data model element is read only',
  [SCORM_ERROR_CODES.WRITE_ONLY_ELEMENT]: 'Data model element is write only',
  [SCORM_ERROR_CODES.DATA_MODEL_ELEMENT_TYPE_MISMATCH]: 'Data model element type mismatch',
  [SCORM_ERROR_CODES.DATA_MODEL_ELEMENT_VALUE_OUT_OF_RANGE]: 'Data model element value out of range',
  [SCORM_ERROR_CODES.DATA_MODEL_DEPENDENCY_NOT_ESTABLISHED]: 'Data model dependency not established'
} as const;